spring.application.name=StudentManagementSystem

spring.datasource.url=jdbc:mysql://2RBx79zGacCmCa5.root:OrkijdnlzSzQ9cGv@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
spring.datasource.username=root

spring.datasource.password=OrkijdnlzSzQ9cGv

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.security.user.name=user
spring.security.user.password=password

server.port=8600
